name: PR Dev build and test
on:
  pull_request:
    branches: [ dev ]
jobs:
  build_test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./advisor-app
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 23.x
        uses: actions/setup-node@v2
        with:
          node-version: 23.x
      - name: npm install, ci, build and test
        run: |
          npm install
          npm ci
          npm run build --if-present
          npm test
