name: Trigger Release

on:
  pull_request:
    branches:
      - dev
    types:
      - closed

jobs:
  trigger-release:
    name: Trigger release Job
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - run: echo "Trigger release Job - triggered"

      - name: Checkout 'dev' # 'marketplace/actions/checkout'
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get next tag # 'marketplace/actions/git-next-tag'
        id: calculate_next_version
        uses: ldelarue/git-next-tag@v0
        with:
          tag-prefix: v

      - name: Create release branch # 'marketplace/actions/create-branch'
        uses: peterjgrainger/action-create-branch@v2.2.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          branch: 'release-${{ steps.calculate_next_version.outputs.tag }}'

      - name: Checkout 'release-${{ steps.calculate_next_version.outputs.tag }}' # 'marketplace/actions/checkout'
        uses: actions/checkout@v4
        with:
          ref: 'release-${{ steps.calculate_next_version.outputs.tag }}'

      - name: Update 'RELEASELOG.txt'
        run: |
          echo $(date +%Z_%Y-%m-%d_%H:%M:%S)_[${{ steps.calculate_next_version.outputs.tag }}] Released new version. >> ${{ github.workspace }}/RELEASELOG.txt
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add .
          git commit -m "Added [${{ steps.calculate_next_version.outputs.tag }}] to RELEASELOG.txt"
          git push origin HEAD
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Checkout 'release-${{ steps.calculate_next_version.outputs.tag }}' # 'marketplace/actions/checkout'
        uses: actions/checkout@v4
        with:
          ref: 'release-${{ steps.calculate_next_version.outputs.tag }}'
          
      - name: Create PR 'release-${{ steps.calculate_next_version.outputs.tag }}' to 'prod' # marketplace/actions/create-pull-request
        uses: peter-evans/create-pull-request@v7
        with:
          branch: 'release-${{ steps.calculate_next_version.outputs.tag }}'
          base: 'prod'
          title: '[${{ steps.calculate_next_version.outputs.tag }}] Integration request'
          body: '[${{ steps.calculate_next_version.outputs.tag }}] Integration request'

      - name: Checkout 'release-${{ steps.calculate_next_version.outputs.tag }}' # 'marketplace/actions/checkout'
        uses: actions/checkout@v4
        with:
          ref: 'prod'

      - name: Create New Tag # 'marketplace/actions/create-tag'
        uses: negz/create-tag@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          version: ${{ steps.calculate_next_version.outputs.tag }}
          message: '[${{ steps.calculate_next_version.outputs.tag }}] Release Tag'

      - name: Backtrack PR 'prod' to 'dev' # marketplace/actions/create-pull-request
        uses: peter-evans/create-pull-request@v7
        with:
          branch: 'prod'
          base: 'dev'
          title: '[Backtrack][${{ steps.calculate_next_version.outputs.tag }}] Integration request'
          body: '[Backtrack][${{ steps.calculate_next_version.outputs.tag }}] Integration request'